"""Added percentage_threshold to scorecard

Revision ID: 7569267de298
Revises: 
Create Date: 2025-04-10 07:55:44.079282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7569267de298'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score_calculations', sa.Column('percentage_threshold', sa.Integer(), nullable=True))
    op.add_column('scorecard_versions', sa.Column('percentage_threshold', sa.Integer(), nullable=True))
    op.add_column('scorecards', sa.Column('percentage_threshold', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scorecards', 'percentage_threshold')
    op.drop_column('scorecard_versions', 'percentage_threshold')
    op.drop_column('score_calculations', 'percentage_threshold')
    # ### end Alembic commands ###
