"""Add decision to ScoreCalculation

Revision ID: fa2488932c9d
Revises: 4235318828c6
Create Date: 2025-04-10 19:14:25.736975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa2488932c9d'
down_revision: Union[str, None] = '4235318828c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score_calculations', sa.Column('decision', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('score_calculations', 'decision')
    # ### end Alembic commands ###
